version: 1
environments:
  - description: Local environment (computercat)
    origins:
      - "https://computercat.tyemirov.net:4443"
    auth:
      tauthUrl: "https://computercat.tyemirov.net:4443"
      googleClientId: "761199429759-ftho7a14blghha4j8bifetrelor0u6sn.apps.googleusercontent.com"
      tenantId: "prompt-bubbles"
      loginPath: "/auth/google"
      logoutPath: "/auth/logout"
      noncePath: "/auth/nonce"
    authButton:
      text: "signin_with"
      size: "large"
      theme: "outline"
  - description: Local environment (test runner)
    origins:
      - "http://127.0.0.1:4173"
    auth:
      tauthUrl: "http://127.0.0.1:4173"
      googleClientId: "761199429759-ftho7a14blghha4j8bifetrelor0u6sn.apps.googleusercontent.com"
      tenantId: "prompt-bubbles"
      loginPath: "/auth/google"
      logoutPath: "/auth/logout"
      noncePath: "/auth/nonce"
    authButton:
      text: "signin_with"
      size: "large"
      theme: "outline"
  - description: Production enviornment
    origins:
      - "https://prompts.mprlab.com"
    auth:
      tauthUrl: "https://tauth-api.mprlab.com"
      googleClientId: "761199429759-ftho7a14blghha4j8bifetrelor0u6sn.apps.googleusercontent.com"
      tenantId: "prompt-bubbles"
      loginPath: "/auth/google"
      logoutPath: "/auth/logout"
      noncePath: "/auth/nonce"
    authButton:
      text: "signin_with"
      size: "large"
      theme: "outline"
